spring:
  application:
    name: flux

  security:
    user:
      name: dev
      password: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/flux
    username: flux
    password: flux

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  sql:
    init:
      mode: never
